### ISSUE TITLE
QThread: Destroyed while thread is still running

### ISSUE THREAD

**Issue by baliwae** [freelacoin/GUI#1]
running on ubuntu 16.04
compile from source.

when first running, it pop up loading blockchain, and than crash.
at terminal it show:
/build$ ./freelabitwallet 
QThread: Destroyed while thread is still running

**Comment by baliwae** [comment]
cli wallet and gui wallet cannot run together. i must close cli wallet (freelabitd) first, so gui can work.

i hope it can work together in next version

**Comment by freelacoin** [comment]
Exactly.
GUI and CLI are not intended to run in the same instance.
Gui wallet has it´s own daemon that starts once you start the GUI wallet.
If you need to run the CLI binaries you may build them from source  from https://github.com/freelacoin/freelabit (instructions on README) once built you may start freelabitd and flbwallet (CLI).
It is not possible to run GUI and CLI wallets together.
